version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - "3002:3000"
    restart: always
    volumes:
      - data:/app/dist/assets

  push-ups-leaderboard:
    build:
     context: ./frontend
     dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3001:3000"

volumes:
  data:
    driver: local