version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
    ports:
      - "3002:3000"
    restart: always
    volumes:
      - ./backend/src/assets/data.json:/app/src/assets/data.json

  push-ups-leaderboard:
    build:
     context: ./frontend
     dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3001:3000"